---
dependencies:
  auto_route: ^0.2.2
  cupertino_icons: ^1.0.1
  dartz: ^0.8.9
  data_connection_checker: ^0.3.4
  dio: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  flutter_secure_storage: ^3.3.1+1
  fluttertoast: ^3.1.3
  freezed: ^0.6.1
  get_it: ^3.0.3
  json_annotation: ^3.0.0
  path_provider: ^1.3.0
description: Full stack Flutter.
dev_dependencies:
  auto_route_generator: ^0.2.2
  build_runner: ^1.0.0
  effective_dart: ^1.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.0.0
  mockito: ^4.1.1
environment:
  sdk: '>=2.7.0 <3.0.0'
flutter:
  assets:
    - assets/
  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext.ttf
        - asset: assets/fonts/AvenirNextBold.ttf
          weight: 700
  uses-material-design: true
name: veram
version: 1.0.0+1